# Generated by Django 5.0.2 on 2024-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_inventory_tag_delete_book_inventory_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
